language: java

jdk:
  - openjdk11

# Replace Travis's default Maven installation step with a no-op.
# This avoids redundantly pre-running 'mvn install -DskipTests' every time.
install: true

# Replace Travis's default build step.
# Run all Maven phases at once up through verify, install, and deploy.
script:
  # only (attempt to) deploy non-pull request commits to the master branch, dev branch, or tags
  # Otherwise, just run all the way up to verify, the last phase before installing and deploying.
  # Setting the gpg.skip property avoids signing artifacts when the encryption keys are not available.
  - |
    if [[ "$TRAVIS_PULL_REQUEST" = false ]] && [[ "$TRAVIS_BRANCH" = master || "$TRAVIS_BRANCH" = dev || ! -z "$TRAVIS_TAG" ]]; then
      mvn clean package --settings maven-settings.xml
    else
      mvn clean verify --settings maven-settings.xml -B -V -Dgpg.skip
    fi

# Secure envs are OSSRH_JIRA_USERNAME, OSSRH_JIRA_PASSWORD (add GPG_KEY_NAME, GPG_PASSPHRASE)
env:
  global:
    secure: "PFNZPkRe83RJY3LEgGwDtF1ZyO1JkXSGaewCt/eseJe75mPr5DYQfLo8IniDwby3gX8TkyzpPcXRpn7WCBDo9J3dkr9naHOO2Qg1lCB0L3IRy/zTATGOs1RfFA86r8oqWhAi4PsDFBebOzUelV4LKDjx2uQ7vpnquBCpt48GjrvlYn5JCH/pFQHrH/w7+U0u+9ZC363xYr7fvDtAHxbe/m73ZK2dxN7Bq5TL/HWb1CvSeLyF+0LyfnovEmPoK3qwh8ckacrT3bI9scbCDCx8NI0c04rDeKQYaINaChNYWJ6s2zqLgm9qdpZ4a8wpe6up94+sHosvGw6LBklT8thJtmSB8TEc2ts6HcM9cKTt3Pk8guPKr7fbMvBMZaIKBufndqEnPF/cUpS8Ta14viuB1UV8LZiHdwQ0C8IPO4LPhvvRKsXmn4DD3kJ7z7eKvs1GUy9j/ZcYo9GbSv9VlG4bqjbF+yJPuQT+9ouSDYJ0GQZKARKd1RIkDU5q0rRiU2LrYq56EUz9yzPQPWTgISKtp6MH/ftC2ffLghf2K2YFvHxWfMZdZLPFcQCBxUyT5IH9wkpOwrGbwuabuQLt9kY7SFB9H6UhtO18OV83v/D8en//BMDbIa7+5QDLTbjZIEFiv2tRYOa0OrLfLZlBcH0WJJD3HPWiNK1VK1V7hqi2GtA="
    secure: "lDKdEuJ1I9EhbkNt9edGWtmmCKtlQJIYcccPge0BMfdSn1fqe/h5g3wKxGH8UGsCfGrBwJsgqr8MdTGW1czjmkPmh0HMFx7tkCQaFeEgJh6/9HCYL7UvCSqA77SWnrRZle0kxATsLo39WRdIGroggO6dCRsav34nZfLMpKSs/myRgEZB89+5ImTn/9a/CPw1RiURvhb09yA+Ol9fDAdiPRg68+KqYIN/HuGgwq+lSuxSA1+pz+FBArTJm4pQU6AEicg4SUPy1IxGe+Qxdm0eGMjBWnNKkVqdok/1BIHKP1DaeMtNJHIKhBjZzf9C8DLRYCr9SjkuMYIgLhfYNInadIWM91xYHjotrgtb43iHO/eckCCADLB7NwDq55Fs2jenz5MXH8Q0BE9jc3NAzRo/ZIBU502hFLPbm6Ighcl8mliz2OQG5XvA+kYRIpKLlmxDK95zV9pHcDVufZL8U42J6dRUZVVXBm745yzzhc+DMYs+pP1hsjvm2cb+Ha79bF68JLX7yeD/u4NZeh3umYTDPtKx2z1nt/8emJmM/DHaY87dZGPIqNjHBXUKdXxjt5hyfHl3ClGoRoeqDWTxzDTF4Wz68HbRZx9Z5pwk6+khLEzM0AcGSlniBAgHxUKw9TSHRpm9+f0m+V9Kjw8lFlcli2pTDNIDuE8p8joe7lSejSo="

# If sudo is disabled, CI runs on container based infrastructure (allows caching &c.)
sudo: false

# Retain the local Maven repository to speed up builds.
# The Conveyal subdirectory is deleted in the script above to prevent retaining Conveyal snapshot artifacts across builds.
cache:
  directories:
    - "$HOME/.m2/repository"

# Notify us of the build status on the Slack channel
notifications:
  slack: conveyal:WQxmWiu8PdmujwLw4ziW72Gc

